matrix:
  include:
    - language: rust
      rust:
        - 1.0.0
        - nightly
      script:
        - cargo build --verbose
        - cargo test --verbose
    - language: verilog
      install:
        - sudo apt-get install -y iverilog
      script:
        - iverilog code/__initVerilog__.v
    - language: go
      install:
        - sudo apt-get install golang-go
      script:
        - go run code/__initgo__.go
